// <auto-generated />
using GeekShopping.ProductAPI.Model.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeekShopping.ProductAPI.Migrations
{
    [DbContext(typeof(MySqlContext))]
    [Migration("20220722124937_SeedProductDataTable")]
    partial class SeedProductDataTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GeekShopping.ProductAPI.Model.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("category_name");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.ToTable("product");

                    b.HasData(
                        new
                        {
                            Id = 2L,
                            CategoryName = "T-Shirt",
                            Description = "Camiseta No Internet personalizada na tematica Jurassic Park",
                            ImageURL = "https://github.com/leandrocgsi/erudio-microservices-dotnet6/blob/main/ShoppingImages/2_no_internet.jpg?raw=true",
                            Name = "Camiseta No Internet",
                            Price = 69.9m
                        },
                        new
                        {
                            Id = 3L,
                            CategoryName = "Action Figure",
                            Description = "Figure do Capecete Darth Vader Star Wars Black Series edição limitada",
                            ImageURL = "https://github.com/leandrocgsi/erudio-microservices-dotnet6/blob/main/ShoppingImages/3_vader.jpg?raw=true",
                            Name = "Capecete Darth Vader Star Wars Black Series",
                            Price = 999.99m
                        },
                        new
                        {
                            Id = 4L,
                            CategoryName = "Action Figure",
                            Description = "Figure de qualidade da série star wars",
                            ImageURL = "https://github.com/leandrocgsi/erudio-microservices-dotnet6/blob/main/ShoppingImages/4_storm_tropper.jpg?raw=true",
                            Name = "Storm Tropper",
                            Price = 169.9m
                        },
                        new
                        {
                            Id = 5L,
                            CategoryName = "Shirt",
                            Description = "Camisa personalizada para aqueles que são 100% Geek",
                            ImageURL = "https://github.com/leandrocgsi/erudio-microservices-dotnet6/blob/main/ShoppingImages/5_100_gamer.jpg?raw=true",
                            Name = "100% Gamer",
                            Price = 29.9m
                        },
                        new
                        {
                            Id = 6L,
                            CategoryName = "Shirt",
                            Description = "Camisa para fãs da space X feita de algodão",
                            ImageURL = "https://github.com/leandrocgsi/erudio-microservices-dotnet6/blob/main/ShoppingImages/6_spacex.jpg?raw=true",
                            Name = "Camisa Space X",
                            Price = 19.9m
                        },
                        new
                        {
                            Id = 7L,
                            CategoryName = "Shirt",
                            Description = "Camisa hiper foda sobre os benefícios do café para viciados em café",
                            ImageURL = "https://github.com/leandrocgsi/erudio-microservices-dotnet6/blob/main/ShoppingImages/7_coffee.jpg?raw=true",
                            Name = "Camisa Coffee drinking",
                            Price = 39.9m
                        },
                        new
                        {
                            Id = 8L,
                            CategoryName = "Sweatshirt",
                            Description = "Moletom preto da série Cobra Kai",
                            ImageURL = "https://github.com/leandrocgsi/erudio-microservices-dotnet6/blob/main/ShoppingImages/8_moletom_cobra_kay.jpg?raw=true",
                            Name = "Moletom Cora Kai",
                            Price = 56m
                        },
                        new
                        {
                            Id = 9L,
                            CategoryName = "Book",
                            Description = "Livro Star Talk com Neil deGrasse Tyson",
                            ImageURL = "https://github.com/leandrocgsi/erudio-microservices-dotnet6/blob/main/ShoppingImages/9_neil.jpg?raw=true",
                            Name = "Stat Talk",
                            Price = 69.9m
                        },
                        new
                        {
                            Id = 10L,
                            CategoryName = "Action Figure",
                            Description = "Action figure da Milennium Falcon dos filmes de Star Wars",
                            ImageURL = "https://github.com/leandrocgsi/erudio-microservices-dotnet6/blob/main/ShoppingImages/10_milennium_falcon.jpg?raw=true",
                            Name = "Milennium Falcon",
                            Price = 499.9m
                        },
                        new
                        {
                            Id = 11L,
                            CategoryName = "Shirt",
                            Description = "Camisa Occupy Mars de algodão preta",
                            ImageURL = "https://github.com/leandrocgsi/erudio-microservices-dotnet6/blob/main/ShoppingImages/11_mars.jpg?raw=true",
                            Name = "Camisa Occupy Mars",
                            Price = 19.9m
                        },
                        new
                        {
                            Id = 12L,
                            CategoryName = "T-Shirt",
                            Description = "Camisa branca escrito Gnu/Linux Freedom",
                            ImageURL = "https://github.com/leandrocgsi/erudio-microservices-dotnet6/blob/main/ShoppingImages/12_gnu_linux.jpg?raw=true",
                            Name = "Camiseta branca Gnu Linux",
                            Price = 19.9m
                        },
                        new
                        {
                            Id = 13L,
                            CategoryName = "T-Shirt",
                            Description = "Camiseta branca com o personagem Goku do anime Dragon ball estampada",
                            ImageURL = "https://github.com/leandrocgsi/erudio-microservices-dotnet6/blob/main/ShoppingImages/13_dragon_ball.jpg?raw=true",
                            Name = "Camiseta do Goku",
                            Price = 59.99m
                        },
                        new
                        {
                            Id = 14L,
                            CategoryName = "",
                            Description = "Logo da Nasa",
                            ImageURL = "https://github.com/leandrocgsi/erudio-microservices-dotnet6/blob/main/ShoppingImages/14_patch_nasa.jpg?raw=true",
                            Name = "Name",
                            Price = 9.9m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
